version: "2.2"
services:
  server:
    image: docker.io/v2ray/official:latest
    restart: unless-stopped
    volumes:
    - ./config/server/config.json:/etc/v2ray/config.json:ro
    ports:
    - 127.0.0.1:33389:33389/tcp
  nginx:
    image: docker.io/nginx:latest
    restart: unless-stopped
    volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    - ./ssl/cert.pem:/etc/nginx/ssl/v2ray.crt:ro
    - ./ssl/cert-key.pem:/etc/nginx/ssl/v2ray.key:ro
    ports:
    - 80:80/tcp
    - 443:443/tcp
  client:
    image: docker.io/v2ray/official:latest
    restart: unless-stopped
    volumes:
    - ./config/client/config.json:/etc/v2ray/config.json:ro
    - ./ssl/ca.pem:/etc/v2ray/ssl/ca.crt:ro
    ports:
    - 127.0.0.1:1080:1080/tcp
